server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

spring:

  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid: #引用dev环境的配置
      driver-class-name: ${sky.datasource.driver-class-name}
      url: ${sky.datasource.url}
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  servlet:
    multipart:   #设置文件传输大小限制
      max-file-size: 10MB
      max-request-size: 100MB
    

mybatis:
  #mapper配置文件
  
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置mybatis的日志, 指定输出到控制台

logging:
  file:
    encoding: UTF-8
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: V1rtual
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  alioss:
  #引用dev环境的配置
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}